baseURL: 
languageCode: en-us
title: Haql
theme: papermod
paginate: 5
author:
  name: "Admin"
copyright: 

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

permalinks:
  posts: "/:year/:month/:slug/"

taxonomies:
  category: categories
  tag: tags
  series: series

related:
  includeNewer: true
  indices:
  - name: keywords
    weight: 10
  - name: date
    weight: 10
  threshold: 5
  toLower: false
  
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: series
      name: Series
      url: /series/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 40

markup:
  highlight:
    # anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: false
    noClasses: false
    style: atom-one-dark

params:
  env: production
  author: ["Admin", "Si Lucu"]
  description: "Some quick summary text to describe the post"
  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: true
  ShowReadingTime: true
  ShowToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true

  homeInfoParams:
    Title: "PaperMod"
    Content: >
      Welcome to demo of hugo's theme PaperMod.
      - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.
      - Do give a 🌟 on Github !
      - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).

  socialIcons:
    - name: github
      url: "https://github.com/deniandriancode"
    - name: instagram
      url: "https://ko-fi.com/adityatelange"
    - name: Rss
      url: "index.xml"

  assets:
    disableHLJS: false

  editPost:
    # URL: "https://github.com/<gitlab user>/<repo name>/tree/<branch name>/<path to content>/" # site config
    URL: "https://github.com/<path_to_repo>/content" # per post
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  cover:
    linkFullImages: false

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 1
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true
